version: 2

models:
  - name: fct_load_audit_summary
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns: [load_event_id, file_id]
    columns:
      - name: load_event_id
        tests: [not_null]
      - name: file_id
        tests: [not_null]
      - name: invoice_line_rows
        tests: [not_null]

  - name: mart_weekly_spend
    columns:
      - name: week_start
        tests: [not_null, unique]
      - name: invoice_line_rows
        tests: [not_null]
      - name: shipment_count
        tests: [not_null]
      - name: total_net_amount
        tests: [not_null]
      - name: total_credits
        tests: [not_null]
      - name: total_charges
        tests: [not_null]

  - name: fct_shipment_cost
    columns:
      - name: tracking_number
        tests: [not_null, unique]
      - name: total_shipment_cost
        tests: [not_null]
      - name: line_count
        tests: [not_null]

  - name: anom_duplicate_charges
    columns:
      - name: tracking_number
        tests: [not_null]

  - name: anom_shipment_cost_outliers
    columns:
      - name: tracking_number
        tests: [not_null]
